#!/bin/bash

source "../install-helpers"

bin_dir="$HOME/bin"
projects_dir="$HOME/projects"

ensure_directory_exists "user binaries" "$bin_dir"
ensure_directory_exists "projects" "$projects_dir"

ensure_symlink_exists "project loader" "$PWD/load-project" "$bin_dir/load-project"
