#!/bin/sh

bin_dir="$HOME/bin"
projects_dir="$HOME/projects"

if [ -f "$bin_dir/load-project" ]; then
  echo "Project loader already exists"
else
  echo "Creating symlink to project loader"
  ln -s "$PWD/load-project" "$bin_dir/load-project"
fi

if [ -d "$projects_dir" ]; then
  echo "Projects directory already exists"
else
  echo "Creating projects directory"
  mkdir "$projects_dir"
fi
