#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CURRENT_DIR/install-helpers"

cd "$CURRENT_DIR" || exit 1

for module in *; do
  module_path="$CURRENT_DIR/$module"
  if [[ -d "$module_path" && ! -L "$module_path" ]]; then
    if [[ -f "$module_path/install" ]]; then
      show_module_title "$module"
      "$module_path"/install
      echo
    fi
  fi
done
