#!/bin/bash -e

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || exit 1

# shellcheck source=install-helpers
source "$DOTFILES_ROOT/install-helpers"

for module_path in "$DOTFILES_ROOT"/*; do
  if [[ -d "$module_path" && ! -L "$module_path" ]]; then
    if [[ -f "$module_path/install.sh" ]]; then
      show_module_title "$(basename "$module_path")"

      # shellcheck source=/dev/null
      source "$module_path/install.sh"

      echo
    fi
  fi
done
