#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CURRENT_DIR/../install-helpers"

if [[ "$(defaults read -g ApplePressAndHoldEnabled)" == "0" ]]; then
  skip_action "Press and hold is already disabled"
else
  perform_action "Disabling press and hold"
  defaults write -g ApplePressAndHoldEnabled -bool false
fi
