colorscheme slate
filetype indent on
filetype plugin on
syntax enable

set ai
set autoread
set backspace=indent,eol,start
set background=dark
set clipboard=unnamed
set cmdheight=2
set cursorline
set encoding=utf-8
set expandtab
set ffs=unix,dos,mac
set hidden
set history=700
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set magic
set mat=2
set mouse=a
set nobackup
set noerrorbells
set noswapfile
set novisualbell
set nowb
set number
set nowrap
set ruler
set shiftwidth=2
set showmatch
set si
set smartcase
set smarttab
set so=7
set tabstop=2
set t_vb=
set tm=500
set wildmenu
set wildmode=longest:full,full
