#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CURRENT_DIR/../install-helpers"

ensure_symlink_exists "tmux configuration file" "$CURRENT_DIR/config/tmux.conf" "$HOME/.tmux.conf"
