#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$CURRENT_DIR/../install-helpers"

PROFILE="$HOME/.zshrc"
touch "$PROFILE"

LOADER="$(cd "$CURRENT_DIR/../shell/scripts" && pwd)/source.sh"
SOURCE_LINE="source $LOADER"

if ! grep -Fqx "$SOURCE_LINE" "$PROFILE"; then
  perform_action "Sourcing shell loader in zsh profile"
  echo "$SOURCE_LINE" >> "$PROFILE"
else
  skip_action "Already sourcing shell loader in zsh profile"
fi
