#!/bin/sh

source "../install-helpers"

PROFILE="$HOME/.bash_profile"
touch "$PROFILE"

for script in *.sh; do
  source_line="source $PWD/$script"
  if [ -z "`grep "$source_line" "$PROFILE"`" ]; then
    perform_action "Sourcing $script in bash profile"
    echo "$source_line" >> "$PROFILE"
  else
    skip_action "Already sourcing $script in bash profile"
  fi
done

source "$PROFILE"
